### ISSUE TITLE
database user and schema creation

### ISSUE THREAD

**Issue by baloan** [NathanVaughn/webtrees-docker#121]
I can't seem to get the docker container to create the user and the database schema `webtrees`. I think it requires access to the root user and thus cannot work with the current setup. I am using an already existing mysql database instance on the host.
I have resorted to creating a user and database schema manually, which works partially: all tables and keys are created but the docker container fails to create the initial adminuser (wt_user table is empty, can't login).
Also it is unclear to me which charset and collation to use for the database schema.
My `docker-compose.yml` (anonymized):
```
version: "3"
services:
  webtrees: 
    image: nathanvaughn/webtrees
    container_name: webtrees
    restart: unless-stopped
    environment:
      - BASE_URL=https://example.com
      - LANG=de
      - DB_TYPE=mysql
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=webtrees
      - DB_NAME=webtrees
      - DB_PASS=webtrees_password
      - DB_PREFIX=wt_
      - WT_USER=john
      - WT_PASS=john_password
      - WT_NAME=John
      - WT_EMAIL=some@email.com
    volumes:
      - data:/var/www/webtrees/data/
      - media:/var/www/webtrees/media/
      - themes:/var/www/webtrees/modules_v4/
volumes:
  data:
  media:
  themes:

```
