### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by ExarchD** [NathanVaughn/webtrees-docker#57]
I can't seem to figure out how to login to the default account. It seems like there's no account creation page to go to if there's not a default.

**Comment by NathanVaughn** [comment]
If you set all the following environment variables:

- `DB_HOST`
- `DB_PASS`
- `WT_NAME`
- `WT_USER`
- `WT_PASS`
- `WT_EMAIL`

then an account will be created with the username defined by `WT_USER` and the password defined by `WT_PASS`. Otherwise, you'll be sent to the setup wizard page like so: 
![image](https://user-images.githubusercontent.com/8636459/117733228-cf98e480-b1b6-11eb-92c8-21175719b35a.png) (using this Docker compose):

```yml
version: "3"

services:
  app:
    depends_on:
      - db
    environment:
      PRETTY_URLS: "1"
      LANG: "en-US"
      BASE_URL: "http://localhost:80/"
      DB_TYPE: "mysql"
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_USER: "webtrees"
      DB_PASS: "badpassword"
      DB_NAME: "webtrees"
      DB_PREFIX: "wt_"
    image: ghcr.io/nathanvaughn/webtrees:latest
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - app_data:/var/www/webtrees/data/
      - app_media:/var/www/webtrees/media/

  db:
    environment:
      MYSQL_DATABASE: "webtrees"
      MYSQL_USER: "webtrees"
      MYSQL_ROOT_PASSWORD: "badpassword"
      MYSQL_PASSWORD: "badpassword"
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
  app_data:
    driver: local
  app_media:
    driver: local

```

This is only in effect the first time you launch the container, and there is no default account. If you haven't filled out the environment variables and you're not getting the setup page, then most likely you already have the file `data/config.ini.php` in your container, or data already exists in your database and you'll need to clear this out and try again.
