### ISSUE TITLE
DB Error in Initialization Wizard

### ISSUE THREAD

**Issue by tmuehlherr** [NathanVaughn/webtrees-docker#82]
Running this in docker desktop on Windows 10. After starting the web UI I enter the two pages of configuration items. Then I get this error: 

```
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'wt_gedcom' already exists (SQL: create table `wt_gedcom` (`gedcom_id` int not null auto_increment primary key, `gedcom_name` varchar(255) not null, `sort_order` int not null default '0') default character set utf8 collate 'utf8_unicode_ci' engine = InnoDB)

#0 /var/www/webtrees/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('create table `w...', Array, Object(Closure))
#1 /var/www/webtrees/vendor/illuminate/database/Connection.php(459): Illuminate\Database\Connection->run('create table `w...', Array, Object(Closure))
#2 /var/www/webtrees/vendor/illuminate/database/Schema/Blueprint.php(97): Illuminate\Database\Connection->statement('create table `w...')
#3 /var/www/webtrees/vendor/illuminate/database/Schema/Builder.php(278): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
#4 /var/www/webtrees/vendor/illuminate/database/Schema/Builder.php(167): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#5 /var/www/webtrees/app/Schema/Migration0.php(44): Illuminate\Database\Schema\Builder->create('gedcom', Object(Closure))
#6 /var/www/webtrees/app/Services/MigrationService.php(71): Fisharebest\Webtrees\Schema\Migration0->upgrade()
#7 /var/www/webtrees/app/Http/RequestHandlers/SetupWizard.php(405): Fisharebest\Webtrees\Services\MigrationService->updateSchema('\\Fisharebest\\We...', 'WT_SCHEMA_VERSI...', 45)
#8 /var/www/webtrees/app/Http/RequestHandlers/SetupWizard.php(366): Fisharebest\Webtrees\Http\RequestHandlers\SetupWizard->createConfigFile(Array)
#9 /var/www/webtrees/app/Http/RequestHandlers/SetupWizard.php(200): Fisharebest\Webtrees\Http\RequestHandlers\SetupWizard->step6Install(Array)
#10 /var/www/webtrees/app/Http/Middleware/ReadConfigIni.php(69): Fisharebest\Webtrees\Http\RequestHandlers\SetupWizard->handle(Object(Nyholm\Psr7\ServerRequest))
#11 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Fisharebest\Webtrees\Http\RequestHandlers\SetupWizard))
#12 /var/www/webtrees/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#13 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#14 /var/www/webtrees/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#15 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#16 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#17 /var/www/webtrees/app/Webtrees.php(241): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#18 /var/www/webtrees/app/Webtrees.php(228): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array)
#19 /var/www/webtrees/index.php(44): Fisharebest\Webtrees\Webtrees->httpRequest()
#20 {main}
```

I dropped the tables in the database and re-ran the same. Same error again. 

WebTrees Image 2021-12-05T17:10:48Z  2.0.19
MariaDB: Linuxserver.io version:- 10.5.13-r0-ls46 Build-date:- 2022-01-29T06:47:05+01:00

Any help is appreciated. 

Thomas

**Comment by NathanVaughn** [comment]
Do you have the Docker commands or `docker-compose.yml` file you are using? I ran this `docker-compose.yml` file on my Windows 11 PC with Docker Desktop, and got through the setup UI without issue.

```yml
version: "3"

services:
  app:
    depends_on:
      - db
    environment:
      PRETTY_URLS: "1"
      # HTTPS: "1"
      # HTTPS_REDIRECT: "1"
      LANG: "en-US"
      BASE_URL: "http://localhost"
      # DB_TYPE: "mysql"
      # DB_HOST: "db"
      # DB_PORT: "3306"
      # DB_USER: "webtrees"
      # DB_PASS: "badpassword"
      # DB_NAME: "webtrees"
      # DB_PREFIX: "wt_"
      # WT_USER: "username"
      # WT_NAME: "Full Name"
      # WT_PASS: "mybadpassword"
      # WT_EMAIL: "me@example.com"
    image: ghcr.io/nathanvaughn/webtrees:latest
    #build: .
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - app_data:/var/www/webtrees/data/
      - app_media:/var/www/webtrees/media/

  db:
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_DATABASE: "webtrees"
      MYSQL_USER: "webtrees"
      MYSQL_ROOT_PASSWORD: "badpassword"
      MYSQL_PASSWORD: "badpassword"
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
  app_data:
    driver: local
  app_media:
    driver: local
```

At the time I tried this, this is Webtrees 2.0.19 and MariaDB 10.6.5

**Comment by NathanVaughn** [comment]
This should be resolved (hopefully) now with the latest push of the `:2.0.21` tag and new entrypoint script. Feel free to reopen if it continues to be a problem.

**Comment by MK87L** [comment]
Hi,

I ran the docker compose file on my synology nas and stumbled upon the same error message. I tried several configuration also one close to the docker compose suggested here. 

Only difference is that as base url I use the ip of my nas in combination with the port. 

First to steps always lead to the error message above. Am I missing something?

**Comment by NathanVaughn** [comment]
What version are you using? Is the database blank? I would also recommend leaving out the `WT_` environment variables and try using the setup wizard manually.

**Comment by MK87L** [comment]
Hi,

I was trying with 

**webtrees: latest**

and **mariadb: latest, 11.4 and 10.11**

My database was always empty, before retry I also always deleted all database files. Container Manager has all necessary rights on the webtrees folder. Files are also created. 

Remarkable is, tht after entering my admin credentials in step two of the onboarding process, actually no error occurs, but the program is not processing to a starting or user page. A php.ini file is also created. But when I am calling the base url again, webtrees starts again with the onboarding steps and then the error occurs. 

Here my last docker-compose:

```
services:
  app:
    depends_on:
      - db
    image: ghcr.io/nathanvaughn/webtrees:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PRETTY_URLS: "1"
      LANG: de
      BASE_URL: "http://myip:8080"
      DB_TYPE: mysql
      DB_HOST: db
      DB_PORT: "3306"
      DB_USER: webtrees
      DB_PASS: db_password
      DB_NAME: webtrees
      DB_PREFIX: wt_
    volumes:
      - /volume1/docker/webtrees/data:/var/www/webtrees/data/
      - /volume1/docker/webtrees/modules_v4:/var/www/webtrees/modules_v4/

  db:
    image: mariadb:latest
    restart: unless-stopped
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_DATABASE: webtrees
      MYSQL_USER: webtrees
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: db_password
    volumes:
      - /volume1/docker/webtrees/db:/var/lib/mysql/
```

Thanks for your fast reaction!
